[package]
name = "rpc-it"
version = "0.4.4"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

[workspace]
members = ["macros"]

# --------------------------------------------- Deps --------------------------------------------- #
[dependencies]
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3"
async-lock = "2.7.0"
bytes = "1.4.0"
flume = "0.11"
derive_setters = { version = "0.1.6", optional = true }
futures-util = { version = "0.3.28", features = ["io", "sink"] }
capture-it = "0.4.3"
bitflags = "2.4.0"
enum-as-inner = "0.6.0"
parking_lot = "0.12.1"
dashmap = "5.5.0"
tokio = { version = "1.32.0", optional = true, features = ["io-util"] }
memchr = { version = "2.5.0", optional = true }
serde_json = { version = "1.0.105", optional = true, features = ["raw_value"] }
rmp = { version = "0.8.12", optional = true }
rmp-serde = { version = "1.1.2", optional = true }
rpc-it-macros = { version = "0.1.3", path = "macros", optional = true }

[features]
default = ["in-memory", "delim-framing", "macros", "service-macros"]
tokio = ["dep:tokio"]
msgpack-rpc = ["dep:rmp", "dep:rmp-serde", "dep:derive_setters"]
jsonrpc = ["dep:serde_json"]
delim-framing = ["dep:memchr"]
in-memory = []
macros = []
service = []
service-macros = ["service", "dep:rpc-it-macros"]

[dev-dependencies]
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["test-util", "tokio-macros", "full"] }
