[package]
name = "rpc-it"
version = "0.10.0"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

[workspace]
members = ["macros"]

# --------------------------------------------- Deps --------------------------------------------- #
[dependencies]
thiserror = "1"
serde = "1.0"
erased-serde = "0.4"
bytes = "1.4.0"
mpsc = { package = "async-channel", version = "2" }
parking_lot = "0.12.1"
hashbrown = "0.14.3"
futures = "0.3"
assert = { version = "1.1.0", package = "static_assertions" }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }


[features]
