[package]
name = "rpc-it"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

[dependencies]
derive_more = "0.99"
derive-new = "0.5"
enum-primitive-derive = "0.2"
num-traits = "0.2"

anyhow = "1"
thiserror = "1"

lockfree-object-pool = "0.1"
dashmap = "5"
flume = "0.10"
async-mutex = "1.4"
parking_lot = "0.12"

typed-builder = "0.12"
