[package]
name = "rpc-it"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

# --------------------------------------------- Deps --------------------------------------------- #
[dependencies]
thiserror = "1"
serde = "1.0"
erased-serde = "0.3"

[features]
tokio = []
futures = []
msgpack-rpc = []
jsonrpc = []
