[package]
name = "rpc-it"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
derive-new = "0.5"
enum-primitive-derive = "0.2"
num-traits = "0.2"

futures = "0.3"

anyhow = "1"
thiserror = "1"

lockfree-object-pool = "0.1"
dashmap = "5"
flume = "0.10"

typed-builder = "0.12"
