[package]
name = "rpc-it"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

# --------------------------------------------- Deps --------------------------------------------- #
[dependencies]
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3"
async-lock = "2.7.0"
bytes = "1.4.0"
flume = "0.11"
derive_setters = "0.1.6"
futures-util = { version = "0.3.28", features = ["io"] }
capture-it = "0.4.3"
bitflags = "2.4.0"
enum-as-inner = "0.6.0"
parking_lot = "0.12.1"
dashmap = "5.5.0"
tokio = { version = "1.32.0", optional = true, features = ["io-util"] }

[features]
default = ["in-memory"]
tokio = ["dep:tokio"]
tokio-tungstenite = ["tokio"]
wasm-bindgen-ws = []
msgpack-rpc = []
jsonrpc = []
json-framing = []
in-memory = []
