[package]
name = "rpc-it"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/kang-sw/rpc-it-rs"
authors = ["kang-sw <ki6080@gmail.com>"]
description = "RPC library for my own demand."
license = "MIT"
exclude = ["doc/"]

# --------------------------------------------- Deps --------------------------------------------- #
[dependencies]
derive_more = "0.99"
derive-new = "0.5"
enum-primitive-derive = "0.2"
num-traits = "0.2"

paste = "1"

anyhow = "1"
thiserror = "1"

lockfree-object-pool = "0.1"
dashmap = "5"
flume = "0.10"
async-mutex = "1.4"
parking_lot = "0.12"
futures-util = "0.3"

typed-builder = "0.12"

smallvec = "1"

# ----------------------------------------- Optional Deps ---------------------------------------- #
futures = { version = "0.3", optional = true }

tokio = { version = "1", default-features = false, optional = true, features = [
    "io-util",
] }

tokio-full = { package = "tokio", version = "1", optional = true, features = [
    "full",
] }

# ------------------------------------------- Dev Deps ------------------------------------------- #
[dev-dependencies]
futures_ringbuf = "0.3"

# ------------------------------------------- Features ------------------------------------------- #
[features]
futures = ["dep:futures"]
tokio = ["dep:tokio"]
dev-tokio-full = ["dep:tokio-full"]

# ------------------------------------------------------------------------------------------------ #
#                                            TEST SETUPS                                           #
# ------------------------------------------------------------------------------------------------ #
[[example]]
name = "tcp"
required-features = ["dev-tokio-full"]

[[test]]
name = "ops"
path = "tests/ops.rs"
required-features = ["dev-tokio-full", "futures"]
